// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MotorcycleRacing.AppDbContexts;

#nullable disable

namespace MotorcycleRacing.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MotorcycleRacing.Entities.MotoGP", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AME")
                        .HasColumnType("int");

                    b.Property<int?>("ARA")
                        .HasColumnType("int");

                    b.Property<int?>("ARG")
                        .HasColumnType("int");

                    b.Property<int?>("AUS")
                        .HasColumnType("int");

                    b.Property<int?>("AUT")
                        .HasColumnType("int");

                    b.Property<int?>("CAT")
                        .HasColumnType("int");

                    b.Property<int?>("FRA")
                        .HasColumnType("int");

                    b.Property<int?>("GBR")
                        .HasColumnType("int");

                    b.Property<int?>("GER")
                        .HasColumnType("int");

                    b.Property<int?>("INA")
                        .HasColumnType("int");

                    b.Property<int?>("ITA")
                        .HasColumnType("int");

                    b.Property<int?>("JPN")
                        .HasColumnType("int");

                    b.Property<int?>("Leader")
                        .HasColumnType("int");

                    b.Property<int?>("MAL")
                        .HasColumnType("int");

                    b.Property<int?>("NED")
                        .HasColumnType("int");

                    b.Property<string>("Nationality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("POR")
                        .HasColumnType("int");

                    b.Property<int?>("Point")
                        .HasColumnType("int");

                    b.Property<int?>("Previous")
                        .HasColumnType("int");

                    b.Property<int?>("QAT")
                        .HasColumnType("int");

                    b.Property<int?>("RSM")
                        .HasColumnType("int");

                    b.Property<string>("Rider")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SPA")
                        .HasColumnType("int");

                    b.Property<int?>("THA")
                        .HasColumnType("int");

                    b.Property<int?>("VAL")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("motos");
                });
#pragma warning restore 612, 618
        }
    }
}
